# Amazon Musical Instruments — meta dataset

In [16]:
from pathlib import Path

import polars as pl

DATA_ROOT = Path("../data/")
DATA_DIR = DATA_ROOT / "amazon_musical_instruments"
ANALYZE_DIR = DATA_ROOT / "analyze"

## meta_Musical_Instruments

In [8]:
META_PATH = DATA_DIR / "meta_Musical_Instruments.jsonl"
meta = pl.scan_ndjson(META_PATH)

meta.collect_schema().names()

['main_category',
 'title',
 'average_rating',
 'rating_number',
 'features',
 'description',
 'price',
 'images',
 'videos',
 'store',
 'categories',
 'details',
 'parent_asin',
 'bought_together']

In [14]:
main_cat = meta.select(pl.col("main_category")).collect().unique()
main_cat

shape: (36, 1)
┌──────────────────────────┐
│ main_category            │
│ ---                      │
│ str                      │
╞══════════════════════════╡
│ All Beauty               │
│ Tools & Home Improvement │
│ AMAZON FASHION           │
│ Home Audio & Theater     │
│ Software                 │
│ …                        │
│ Health & Personal Care   │
│ Entertainment            │
│ Arts, Crafts & Sewing    │
│ Books                    │
│ Automotive               │
└──────────────────────────┘

In [15]:
main_cat.count()

shape: (1, 1)
┌───────────────┐
│ main_category │
│ ---           │
│ u32           │
╞═══════════════╡
│ 35            │
└───────────────┘

In [17]:
main_cat.write_csv(ANALYZE_DIR / "main_categories.csv")

In [10]:
meta.head(1).collect()

shape: (1, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ main_cate ┆ title     ┆ average_r ┆ rating_nu ┆ … ┆ categorie ┆ details   ┆ parent_as ┆ bought_t │
│ gory      ┆ ---       ┆ ating     ┆ mber      ┆   ┆ s         ┆ ---       ┆ in        ┆ ogether  │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ struct[10 ┆ ---       ┆ ---      │
│ str       ┆           ┆ f64       ┆ i64       ┆   ┆ list[str] ┆ 8]        ┆ str       ┆ null     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Musical   ┆ Pearl     ┆ 4.2       ┆ 22        ┆ … ┆ ["Musical ┆ {"33 poun ┆ B01M4HO6R ┆ null     │
│ Instrumen ┆ Export    ┆           ┆           ┆   ┆ Instrumen ┆ ds","22 x ┆ K         ┆          │
│ ts        ┆ Lacquer   ┆           ┆           ┆   ┆ ts",      ┆ 22 x 20   ┆           ┆          │
│           ┆ EXL725S/C ┆           ┆           ┆   ┆ "Drums…   ┆ inc…      ┆           ┆          │
│           ┆ …         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘